from typing import Protocol

class PaymentProvider(Protocol):
    async def start(self, user_id: int, amount: int, currency: str) -> tuple[str, str]: ...
    async def check(self, external_id: str) -> bool: ...
